modLoader = "javafml" #mandatory

loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "GNU General Public License v3.0"

issueTrackerURL="https://github.com/Snugzy/Truly-Treasures/issues" #optional

[[mods]] #mandatory

modId = "trulytreasures" #mandatory

version = "1.16.5-2.2.2" #mandatory

displayName = "Truly Treasures" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/truly-treasures" #optional

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL = "https://change.me.example.invalid/updates.json" #optional

logoFile = "truly_treasures_logo.png" #optional

authors = "Snugzy" #optional

credits = "" #optional

description = '''A simple mod to remove treasure enchantments from villager trades and add them to wandering traders instead, in order to make them truly rare and special enchantments'''
