modLoader = "javafml" #mandatory

loaderVersion = "[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "GNU Lesser General Public License v3.0"

issueTrackerURL="https://github.com/Snugzy/Truly-Treasures/issues" #optional

[[mods]] #mandatory

modId = "trulytreasures" #mandatory

version = "1.18.1-2.2.3" #mandatory

displayName = "Truly Treasures" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/truly-treasures" #optional

logoFile = "truly_treasures_logo.png" #optional

authors = "Snugzy" #optional

credits = "" #optional

description = '''Highly configurable mod that makes wandering traders sell treasure enchantments instead of villagers, making them truly rare and special enchantments'''
