modLoader = "javafml" #mandatory

loaderVersion = "[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "GNU General Public License v3.0"

issueTrackerURL="https://github.com/Snugzy/Truly-Treasures-Forge/issues" #optional

[[mods]] #mandatory

modId = "trulytreasures" #mandatory

version = "1.18-2.2.1" #mandatory

displayName = "Truly Treasures" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/truly-treasures" #optional

logoFile = "truly_treasures_logo.png" #optional

authors = "Snugzy" #optional

credits = "" #optional

description = '''A simple mod to remove treasure enchantments from villager trades and add them to wandering traders instead, in order to make them truly rare and special enchantments'''
